version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
    time: "12:00"
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "12:00"
  open-pull-requests-limit: 10
  assignees:
  - PHLAK
